---
# Kodi media center

kodi_enabled: false
kodi_packages:
  - kodi
  - chezmoi

# Media player and codecs
kodi_media_enabled: false
kodi_media_packages:
  - mpv
  - gst-plugins-bad
  - gst-plugins-ugly

# Common addons
kodi_addons_enabled: false
kodi_addon_packages:
  - kodi-addon-inputstream-adaptive
  - kodi-addon-peripheral-joystick

# AUR packages
kodi_aur_enabled: false
kodi_aur_packages:
  - zen-browser-bin

# Auto-mount USB drives
kodi_automount_enabled: false
kodi_automount_packages:
  - udisks2
  - udiskie

# Autologin and start i3 on tty1
kodi_autologin_enabled: false
kodi_autologin_user: "{{ ansible_user_id }}"
