---
# Kodi media center

kodi_enabled: false
kodi_packages:
  - kodi

# Media player and codecs
kodi_media_enabled: false
kodi_media_packages:
  - mpv
  - gst-plugins-bad
  - gst-plugins-ugly

# Common addons
kodi_addons_enabled: false
kodi_addon_packages:
  - kodi-addon-inputstream-adaptive
  - kodi-addon-peripheral-joystick

# Autologin and start i3 on tty1
kodi_autologin_enabled: false
kodi_autologin_user: "{{ ansible_user_id }}"
