---
# Ansible Galaxy requirements
collections:
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.posix
    version: ">=1.5.0"

# Add Galaxy roles as needed
roles: []
  # - src: geerlingguy.docker
  #   version: 7.0.2
